name: Build and Push Docker Image

on:
  push:
    branches:
      - main # 当推送到main分支时触发
    # paths:
    #   - 'Dockerfile' # 仅当Dockerfile改变时触发 (可选)
  pull_request:
    branches:
      - main # 当向main分支发起Pull Request时触发

env:
  REGISTRY: ghcr.io # 或者 docker.io 如果推送到Docker Hub
  IMAGE_NAME: ${{ github.repository }} # 使用仓库名称作为镜像名称

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # 允许将镜像推送到GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # 使用GitHub Token进行GitHub Packages认证

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Dockerfile所在的上下文路径
          push: ${{ github.event_name != 'pull_request' }} # PR时不推送，只构建
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # 启用GitHub Actions缓存
          cache-to: type=gha,mode=max # 将缓存写入GitHub Actions